### ISSUE TITLE
unable to read proerty ID

### ISSUE THREAD

**Issue by norwayRP** [saul-avikar/discord-application-bot#10] opened 2021-02-07 11:23 UTC
Hi

The bot keeps sending me "I could not run that command" not sure why other than it looks like something with a role. The BOY has admin rights.

This is the message.

`Logged in as Application Bot#3674!
TypeError: Cannot read property 'id' of undefined
    at authorAuthorization (C:\FXServer\discord-application-bot\actions.js:17:56)
    at Object.setsubmissions (C:\FXServer\discord-application-bot\actions.js:151:8)
    at C:\FXServer\discord-application-bot\index.js:27:21
    at Array.forEach (<anonymous>)
    at Client.<anonymous> (C:\FXServer\discord-application-bot\index.js:18:20)
    at Client.emit (events.js:315:20)
    at MessageCreateAction.handle (C:\FXServer\discord-application-bot\node_modules\discord.js\src\client\actions\MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (C:\FXServer\discord-application-bot\node_modules\discord.js\src\client\websocket\handlers\MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (C:\FXServer\discord-application-bot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (C:\FXServer\discord-application-bot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:444:22)`

Hope you can help out.

**Comment by saul-jb** [comment] 2021-02-07 19:51
Fixed as of 9c820f32b9681d9fbebbbb5caef5e2c53bd46c9a 
It was caused by the role being the wrong case so I have removed the case requirement for roles.

**Closed as completed by saul-jb** 2021-02-07 19:51 UTC
